### PR TITLE
feat: Added style and className to ScrollPage

### PR DESCRIPTION
**Pull request by MaxiMittel**
Added `style` and `className` props to ScrollPage.

### CODE REVIEW

**Comment by jlputter** [comment]
@1000ship please try to get this pr in soon, would be extremely helpful for customisation. At the moment ScrollPage has a fixed height, which makes it impossible to properly style a page and use the scroll animations.

**Comment by masafumimori** [comment]
@jlputter I totally agree with you!

Well... It's been almost 2 months since this PR was created and the package hasn't had any updates for half a year.
So as a workaround, I created a temporary branch and set it up to use as a npm package [here](https://github.com/masafumimori/react-scroll-motion/tree/temporary). (I couldn't wait for PR to be merged as I have a tight schedule to finish my project.)

=== DISCLAIMER ===
USE IT AT YOUR OWN RISK AS IT MAY CAUSE SOME ISSUES AND MAY NOT WORK PROPERLY

To use this, run command
```shell
yarn add https://github.com/masafumimori/react-scroll-motion.git#temporary
// or
npm install https://github.com/masafumimori/react-scroll-motion.git#temporary --save
```

then, in `package.json` it should be like below and ready to use additional styles and classNames in the package.
```
"dependencies": {
    // other packages
    "react-scroll-motion": "https://github.com/masafumimori/react-scroll-motion.git#temporary"
}
```

I tried this on my project and it seems to be working fine.

Hope this helps others.

**Comment by 1000ship** [comment]
Sorry too busy now. 🙏
I just checked code difference, and I think there's no problem.
At first I gonna accept this PR, Believe you guys!

**Comment by 1000ship** [comment]
I just published this version to npm as 0.3.2
Again, I'm sorry for delaying to merge this PR.
Appreciate!

**Pull request merged**
